### ISSUE TITLE
Foreground Persmission Android 9

### ISSUE THREAD

**Issue by tuwrraphael** [tuwrraphael/digit-app-android#4]
2019-08-07 13:50:31.452 28731-28731/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: digit.digitapp, PID: 28731
    java.lang.RuntimeException: Unable to start service digit.digitapp.DigitSyncService1@2b5f4c6 with Intent { cmp=digit.digitapp/.DigitSyncService1 }: java.lang.SecurityException: Permission Denial: startForeground from pid=28731, uid=10187 requires android.permission.FOREGROUND_SERVICE
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3724)
        at android.app.ActivityThread.access$1600(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=28731, uid=10187 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5202)
        at android.app.Service.startForeground(Service.java:695)
        at digit.digitapp.DigitSyncService1.onStartCommand(DigitSyncService1.java:138)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
        at android.app.ActivityThread.access$1600(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9204)
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1189)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:870)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:20503)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:977)

**Comment by hassan963** [comment]
I have found a solution for this issue, should I give a pull request?

**Comment by tuwrraphael** [comment]
Sure contributions are always welcome. I suspect that it needs the permission defined in the manifest, but I had no time to test yet.

**Comment by hassan963** [comment]
Please check this answer, Apps targeting Android 9 (API level 28) or higher and use foreground services must request the `FOREGROUND_SERVICE` permission. I could not test the app as you did not push `DigitServiceClientConfig `file. Below link might help you.

[https://stackoverflow.com/a/52382711/6668339](url)

**Comment by tuwrraphael** [comment]
Yes sorry. The servers described by the `DigitServiceClientConfig` all use OAuth, it would not be a problem to have them public in general. The thing is that when I have URLs in my public GitHub repos bots start to send random request to them - I have no solution for that at the moment.

However I implemented the fix and will test on monday on a real android 9 device.

**Comment by tuwrraphael** [comment]
works

**Comment by hassan963** [comment]
> 
> 
> works

Happy to help.
